# Generated by Django 3.1.1 on 2020-09-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managebook', '0003_auto_20200919_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='smth', unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, help_text='введите название книги', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
